stages:
  - lint
  - testing
  - push
  - deploy

variables:
  PROJECT_PATH: src/pr7

linting:
  stage: lint
  trigger:
    strategy: depend
    include:
      - local: pipelines/python-linter.yml
  variables:
    REQUIREMENTS_PATH: $PROJECT_PATH

testing:
  stage: testing
  needs:
    - linting
  trigger:
    strategy: depend
    include:
      - local: pipelines/python-tests.yml
  variables:
    PROJECT_PATH: ${PROJECT_PATH}/auth_service/app.py
    TEST_PATH: auto_tests/test_auth.py
    REQUIREMENTS_PATH: src/pr7

push:
  stage: push
  needs:
    - testing
  trigger:
    strategy: depend
    include:
      - local: pipelines/push.yml
  variables:
    REQUIREMENTS_PATH: $PROJECT_PATH

deploy:
  stage: deploy
  needs:
    - push
  trigger:
    strategy: depend
    include:
      - local: pipelines/deploy.yml
