stages:
  - testing

pr2:run-tests:
  stage: testing
  image: python:$PYTHON_VERSION
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r pr2/requirements.txt
    - flake8 --config=confs/.flake8 --statistics pr2/test_calculator.py pr2/calculator.py
    - pytest

notify_on_fail_check-dev:
  stage: testing
  allow_failure: true
  needs:
    - pr2:run-tests
  script:
    - >
      curl 
      -X POST 
      -H "Content-Type: application/json" 
      -d "{\"parse_mode\": \"HTML\",
      \"chat_id\": \"$TG_CHAT_ID\", 
      \"text\": \"🔴Джоба pr2:run-tests провалилась
      \nПроект <b>$CI_PROJECT_NAME</b> 
      \nИнициатор <b>$GITLAB_USER_NAME</b>
      \nОписание коммита <b>$CI_COMMIT_TITLE</b>
      \nХеш коммита <b>$CI_COMMIT_SHA</b>\"}" 
      https://api.telegram.org/bot$TG_BOT_TOKEN/sendMessage
  when: on_failure

