stages:
  - lint
  - testing
  - build

linting:
  stage: lint
  trigger:
    strategy: depend
    include:
      - local: pipelines/python-linter.yml
  variables:
    PROJECT_PATH: src/pr3
    REQUIREMENTS_PATH: src/pr3

testing:
  stage: testing
  trigger:
    strategy: depend
    include:
      - local: pipelines/python-tests.yml
  variables:
    PROJECT_PATH: src/pr3
    REQUIREMENTS_PATH: src/pr3