stages:
  - lint
  - testing

.base:
  tags:
    - security
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r $PROJECT_PATH/requirements.txt

include:
  - local: pipelines/pr2.yml

