services:
  postgres:
    image: postgres:14.17
    container_name: postgres-flask
    restart: always
    volumes:
      - ${POSTGRES_PATH}:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}

  web:
    depends_on:
      - postgres
    image: ${PROD_IMAGE}
    container_name: flask-app
    ports:
      - '80:5000'
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ${PROMETHEUS_PATH}:/etc/prometheus/prometheus.yml
      - ${ALERT_PATH}:/etc/prometheus/alert_rules.yml
    ports:
      - '9090:9090'
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    restart: always

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - '3100:3100'
    volumes:
      - ${LOKI_PATH}:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    restart: always

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PROMTAIL_PATH}:/etc/promtail/promtail.yaml
      - /tmp:/tmp
    command:
      - -config.file=/etc/promtail/promtail.yaml
    ports:
      - '9080:9080'
    restart: always

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker
    restart: always

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ${ALERTMANAGER_PATH}:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    restart: always