version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: panda1basic/flask-app:latest
    container_name: flask-app
    ports:
      - '80:5000'
    restart: always
