global:
  scrape_interval: 5s

rule_files:
  - 'alert_rules.yml'

scrape_configs:
  - job_name: 'flask-app-metrics'
    static_configs:
      - targets: ['flask-app:80']

  - job_name: 'cadvisor'
    metrics_path: /metrics
    static_configs:
      - targets: ['cadvisor:8080']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'