apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: ClusterIP
  selector:
    app: flask-app
  ports:
    - name: http
      port: 80               # внутри кластера
      targetPort: 5000       # на контейнер