global:
  resolve_timeout: 5m

route:
  receiver: telegram
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: telegram
    telegram_configs:
      - bot_token: "7569232236:AAEz4EcMzqDuAZMFgUcBUGkljaXiIo6D6XU"
        chat_id: 840348837
        message: |
          {{- range .Alerts }}
          *[{{ .Status }}]* {{ .Labels.alertname }}
          > {{ .Annotations.summary }}
          {{- if .Annotations.description }}
          _{{ .Annotations.description }}_
          {{- end }}
          *Время:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{- end }}
        parse_mode: Markdown
        send_resolved: true