groups:
  - name: flask-test
    rules:
      - alert: TestAlert
        expr: vector(1)
        for: 1m
        labels:
          severity: info
        annotations:
          summary: "🧪 Это тестовое уведомление"
          description: "Alertmanager → Telegram работает корректно"
