groups:
  - name: flask-app-availability
    rules:
      - alert: FlaskAppContainerDown
        expr: absent(container_last_seen{container="flask-app"})
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "❌ Контейнер flask-app не найден"
          description: "cAdvisor не обнаружил контейнер flask-app более 2 минут"