name: CI & CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install pr2 dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r src/pr2/requirements.txt

      - name: Run calculator tests
        run: |
          . venv/bin/activate
          pytest auto_tests/test_calculator.py

  build-and-push:
    name: Build & Push Flask Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push flask-app image
        uses: docker/build-push-action@v4
        with:
          context: src/pr3
          file: src/pr3/Dockerfile
          push: true
          tags: |
            panda1basic/flask-app:latest
            panda1basic/flask-app:${{ github.sha }}

      - name: Smoke-test /metrics endpoint
        run: |
          docker run -d --name smoke-flask -p 5000:5000 panda1basic/flask-app:latest
          for i in {1..10}; do
            if curl -s http://localhost:5000/metrics; then
              echo "Metrics endpoint is up"
              break
            fi
            echo "Waiting for /metrics..."
            sleep 1
          done
          docker rm -f smoke-flask

  compose-check:
    name: Docker Compose Check
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Copy .env into compose dir
        run: |
          cp src/pr3/.env src/pr3/.env

      - name: Pull Docker images with env
        working-directory: src/pr3
        run: |
          docker-compose --env-file .env pull

      - name: Bring up compose stack with env
        working-directory: src/pr3
        run: |
          docker-compose --env-file .env down || true
          docker-compose --env-file .env up -d
          sleep 10

      - name: List running containers
        working-directory: src/pr3
        run: |
          docker-compose --env-file .env ps
