name: CI & CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run Python Tests
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Expose repo root to PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install all requirements
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          find src -type f -name requirements.txt \
            | xargs -n1 pip install -r

      - name: Run pytest
        run: |
          . venv/bin/activate
          pytest auto_tests

  build-and-push:
    name: Build & Push Docker Image
    runs-on: self-hosted
    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: src/pr3
          file: src/pr3/Dockerfile
          push: true
          tags: |
            panda1basic/flask-app:latest
            panda1basic/flask-app:${{ github.sha }}

  deploy:
    name: Deploy on Self-Hosted VM
    runs-on: self-hosted
    needs: build-and-push

    steps:
      - uses: actions/checkout@v3

      - name: Deploy containers via Docker Compose
        working-directory: src/pr3
        run: |
          # Подтягиваем свежий образ и поднимаем контейнер
          docker-compose -f docker-compose.dev.yml pull || true
          docker-compose -f docker-compose.dev.yml up -d
