name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTEST_ADDOPTS: --maxfail=1 --disable-warnings -q
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Expose src/ to Python
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r src/pr2/requirements.txt
          # pip install -r src/pr7/requirements.txt
          # pip install -r src/pr8/requirements.txt

      - name: Run tests
        run: |
          . venv/bin/activate
          pytest auto_tests
